#!/bin/bash
 
#Taking input the number is how many columns will be created
echo "Enter Number:" 
read number
 
#Outer loop for printing number of column in pyramid
for((column=0;column<=number-1;column++))
do

 #Loop for printing required spaces
for((spaces=0;spaces<=number;spaces++))
do
echo -ne " "
done
 
#Loop for printing 1st part
for((j=0;j<=column;j++))
do
echo -ne "$j "
done
echo
done

#Outer loop for printing number of column 2nd part in pyramid
for((column2=column-1; column2>=0; column2--))
do

 #Loop for printing required spaces
for((spaces2=number;spaces2>=0;spaces2--))
do
echo -ne " "
done
 
#Loop for printing 1st part
for((i=0;i<=(column2-1);i++))
do
echo -ne "$i "
done

#echo for printing new line
echo
done


